project_id = "<PROJECT ID>"
region     = "europe-west1"
zone       = "europe-west1-b"
subnetwork = "projects/<PROJECT ID>/regions/europe-west1/subnetworks/default"
service_account_email = "CAMBIAR ESTO A TU SERVICE ACCOUNT"