{
 "title": "New dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total messages received",
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "WITH total_unmatched_requests AS (\r\n  SELECT COUNT(*) AS total\r\n  FROM `total-glider-447114-u4.users.unmatched_requests`\r\n),\r\ntotal_unmatched_volunteers AS (\r\n  SELECT COUNT(*) AS total\r\n  FROM `total-glider-447114-u4.users.unmatched_volunteers`\r\n),\r\ntotal_matched_pairs AS (\r\n  SELECT COUNT(*) * 2 AS total\r\n  FROM `total-glider-447114-u4.users.matched_pairs`\r\n)\r\n\r\nSELECT \r\n  (total_unmatched_requests.total + total_unmatched_volunteers.total + total_matched_pairs.total) AS total_messages\r\nFROM total_unmatched_requests, total_unmatched_volunteers, total_matched_pairs;\r\n"
    }
   ]
  },
  {
   "title": "Nº of matches by Location",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "WITH total_matched_pairs AS (\r\n  SELECT \r\n    COUNT(*) AS total,\r\n    help_poblacion\r\n  FROM `total-glider-447114-u4.users.matched_pairs`\r\n  GROUP BY help_poblacion\r\n)\r\n\r\nSELECT \r\n  help_poblacion,\r\n  total\r\nFROM total_matched_pairs\r\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Nº of matches by Category",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "WITH total_matched_pairs AS (\r\n  SELECT \r\n    COUNT(*) AS total,\r\n    categoria\r\n  FROM `total-glider-447114-u4.users.matched_pairs`\r\n  GROUP BY categoria\r\n)\r\n\r\nSELECT \r\n  categoria,\r\n  total\r\nFROM total_matched_pairs\r\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of matches and not matches",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "WITH total_unmatched_requests AS (\r\n  SELECT COUNT(*) AS total\r\n  FROM `total-glider-447114-u4.users.unmatched_requests`\r\n),\r\ntotal_unmatched_volunteers AS (\r\n  SELECT COUNT(*) AS total\r\n  FROM `total-glider-447114-u4.users.unmatched_volunteers`\r\n),\r\ntotal_matched_pairs AS (\r\n  SELECT COUNT(*) AS total\r\n  FROM `total-glider-447114-u4.users.matched_pairs`\r\n)\r\n\r\nSELECT \r\n  total_matched_pairs.total AS total_matches,\r\n  (total_unmatched_requests.total + total_unmatched_volunteers.total) AS total_not_matched\r\nFROM total_unmatched_requests, total_unmatched_volunteers, total_matched_pairs;\r\n"
    }
   ]
  },
  {
   "title": "Avg emergency level of help requests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "WITH total_unmatched_requests AS (\r\n  SELECT COUNT(*) AS total, categoria, nivel_urgencia AS urgencia\r\n  FROM `total-glider-447114-u4.users.unmatched_requests`\r\n  GROUP BY categoria, nivel_urgencia\r\n),\r\ntotal_matched_pairs AS (\r\n  SELECT COUNT(*) AS total, categoria, urgencia\r\n  FROM `total-glider-447114-u4.users.matched_pairs`\r\n  GROUP BY categoria, urgencia\r\n)\r\n\r\nSELECT \r\n  categoria,\r\n  AVG(urgencia) AS urgencia_promedio\r\nFROM (\r\n  SELECT categoria, urgencia FROM total_unmatched_requests\r\n  UNION ALL\r\n  SELECT categoria, urgencia FROM total_matched_pairs\r\n)\r\nGROUP BY categoria\r\nORDER BY urgencia_promedio DESC;\r\n"
    }
   ]
  },
  {
   "title": "Nº of not matched requests by Location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "SELECT COUNT(*) as total, poblacion FROM `total-glider-447114-u4.users.unmatched_requests` GROUP BY poblacion ORDER BY total DESC"
    }
   ]
  },
  {
   "title": "Nº of not matched requests by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "project": "total-glider-447114-u4",
     "rawSql": "SELECT COUNT(*) as total, categoria FROM `total-glider-447114-u4.users.unmatched_requests` GROUP BY categoria ORDER BY total DESC"
    }
   ]
  }
 ]
}