project_id = "dataproject2425"
region     = "europe-west1"
zone       = "europe-west1-b"
repository_id = "data-project2"
image_name = "launcher-automatic"
image_name_service = "streamlit"
tag = "v1"
build_context_dir = "../app/launcher/automatic"
build_context_dir_service = "../Streamlit"
job_name = "generadores-job-automatic"
service_name = "streamlit"
grafana_service_name = "grafana"

discord_image_name = "discord-notifier"
discord_tag        = "latest"